// Code generated by protoc-gen-go. DO NOT EDIT.
// source: push.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	push.proto

It has these top-level messages:
	PushResponse
	Info
	Emergency
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type PushResponse struct {
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
}

func (m *PushResponse) Reset()                    { *m = PushResponse{} }
func (m *PushResponse) String() string            { return proto1.CompactTextString(m) }
func (*PushResponse) ProtoMessage()               {}
func (*PushResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PushResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type Info struct {
	DeviceTokens []string   `protobuf:"bytes,1,rep,name=deviceTokens" json:"deviceTokens,omitempty"`
	Emergency    *Emergency `protobuf:"bytes,2,opt,name=emergency" json:"emergency,omitempty"`
}

func (m *Info) Reset()                    { *m = Info{} }
func (m *Info) String() string            { return proto1.CompactTextString(m) }
func (*Info) ProtoMessage()               {}
func (*Info) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Info) GetDeviceTokens() []string {
	if m != nil {
		return m.DeviceTokens
	}
	return nil
}

func (m *Info) GetEmergency() *Emergency {
	if m != nil {
		return m.Emergency
	}
	return nil
}

type Emergency struct {
	Address       string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	AddressNumber string `protobuf:"bytes,2,opt,name=addressNumber" json:"addressNumber,omitempty"`
	PostalCode    string `protobuf:"bytes,3,opt,name=postalCode" json:"postalCode,omitempty"`
	Place         string `protobuf:"bytes,4,opt,name=place" json:"place,omitempty"`
	Lat           string `protobuf:"bytes,5,opt,name=lat" json:"lat,omitempty"`
	Lng           string `protobuf:"bytes,6,opt,name=lng" json:"lng,omitempty"`
	Time          string `protobuf:"bytes,7,opt,name=time" json:"time,omitempty"`
	IsActive      bool   `protobuf:"varint,8,opt,name=isActive" json:"isActive,omitempty"`
}

func (m *Emergency) Reset()                    { *m = Emergency{} }
func (m *Emergency) String() string            { return proto1.CompactTextString(m) }
func (*Emergency) ProtoMessage()               {}
func (*Emergency) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Emergency) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Emergency) GetAddressNumber() string {
	if m != nil {
		return m.AddressNumber
	}
	return ""
}

func (m *Emergency) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *Emergency) GetPlace() string {
	if m != nil {
		return m.Place
	}
	return ""
}

func (m *Emergency) GetLat() string {
	if m != nil {
		return m.Lat
	}
	return ""
}

func (m *Emergency) GetLng() string {
	if m != nil {
		return m.Lng
	}
	return ""
}

func (m *Emergency) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Emergency) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func init() {
	proto1.RegisterType((*PushResponse)(nil), "proto.PushResponse")
	proto1.RegisterType((*Info)(nil), "proto.Info")
	proto1.RegisterType((*Emergency)(nil), "proto.Emergency")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PushService service

type PushServiceClient interface {
	// Send Notifications to a list of Account's devices and return Response
	SendNotifications(ctx context.Context, in *Info, opts ...grpc.CallOption) (*PushResponse, error)
}

type pushServiceClient struct {
	cc *grpc.ClientConn
}

func NewPushServiceClient(cc *grpc.ClientConn) PushServiceClient {
	return &pushServiceClient{cc}
}

func (c *pushServiceClient) SendNotifications(ctx context.Context, in *Info, opts ...grpc.CallOption) (*PushResponse, error) {
	out := new(PushResponse)
	err := grpc.Invoke(ctx, "/proto.PushService/SendNotifications", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PushService service

type PushServiceServer interface {
	// Send Notifications to a list of Account's devices and return Response
	SendNotifications(context.Context, *Info) (*PushResponse, error)
}

func RegisterPushServiceServer(s *grpc.Server, srv PushServiceServer) {
	s.RegisterService(&_PushService_serviceDesc, srv)
}

func _PushService_SendNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Info)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).SendNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PushService/SendNotifications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).SendNotifications(ctx, req.(*Info))
	}
	return interceptor(ctx, in, info, handler)
}

var _PushService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PushService",
	HandlerType: (*PushServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendNotifications",
			Handler:    _PushService_SendNotifications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "push.proto",
}

func init() { proto1.RegisterFile("push.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcf, 0x4e, 0x32, 0x31,
	0x14, 0xc5, 0xbf, 0x7e, 0x30, 0xc0, 0x5c, 0x30, 0xc1, 0xab, 0x8b, 0x86, 0x85, 0x99, 0x34, 0x2e,
	0x66, 0xc5, 0x02, 0x17, 0xae, 0x8d, 0xd1, 0xc4, 0x0d, 0x31, 0xc5, 0x95, 0xbb, 0xa1, 0x73, 0x81,
	0x46, 0x68, 0x27, 0xd3, 0x0e, 0x89, 0x0f, 0xea, 0xfb, 0x98, 0x96, 0x01, 0x61, 0xd5, 0x73, 0x7e,
	0xf7, 0xa4, 0x7f, 0x4e, 0x01, 0xaa, 0xc6, 0x6d, 0xa6, 0x55, 0x6d, 0xbd, 0xc5, 0x24, 0x2e, 0x42,
	0xc0, 0xe8, 0xbd, 0x71, 0x1b, 0x49, 0xae, 0xb2, 0xc6, 0x11, 0x22, 0x74, 0x95, 0x2d, 0x89, 0xb3,
	0x8c, 0xe5, 0x89, 0x8c, 0x5a, 0x7c, 0x42, 0xf7, 0xcd, 0xac, 0x2c, 0x0a, 0x18, 0x95, 0xb4, 0xd7,
	0x8a, 0x3e, 0xec, 0x17, 0x19, 0xc7, 0x59, 0xd6, 0xc9, 0x53, 0x79, 0xc1, 0x70, 0x0a, 0x29, 0xed,
	0xa8, 0x5e, 0x93, 0x51, 0xdf, 0xfc, 0x7f, 0xc6, 0xf2, 0xe1, 0x6c, 0x7c, 0x38, 0x71, 0xfa, 0x72,
	0xe4, 0xf2, 0x2f, 0x22, 0x7e, 0x18, 0xa4, 0xa7, 0x01, 0x72, 0xe8, 0x17, 0x65, 0x59, 0x93, 0x73,
	0xf1, 0x02, 0xa9, 0x3c, 0x5a, 0xbc, 0x87, 0xab, 0x56, 0xce, 0x9b, 0xdd, 0x92, 0xea, 0xb8, 0x77,
	0x2a, 0x2f, 0x21, 0xde, 0x01, 0x54, 0xd6, 0xf9, 0x62, 0xfb, 0x1c, 0xde, 0xd0, 0x89, 0x91, 0x33,
	0x82, 0xb7, 0x90, 0x54, 0xdb, 0x42, 0x11, 0xef, 0xc6, 0xd1, 0xc1, 0xe0, 0x18, 0x3a, 0xdb, 0xc2,
	0xf3, 0x24, 0xb2, 0x20, 0x23, 0x31, 0x6b, 0xde, 0x6b, 0x89, 0x59, 0x87, 0x5e, 0xbc, 0xde, 0x11,
	0xef, 0x47, 0x14, 0x35, 0x4e, 0x60, 0xa0, 0xdd, 0x93, 0xf2, 0x7a, 0x4f, 0x7c, 0x90, 0xb1, 0x7c,
	0x20, 0x4f, 0x7e, 0xf6, 0x0a, 0xc3, 0xd0, 0xeb, 0x82, 0xea, 0x50, 0x0e, 0x3e, 0xc2, 0xf5, 0x82,
	0x4c, 0x39, 0xb7, 0x5e, 0xaf, 0xb4, 0x2a, 0xbc, 0xb6, 0xc6, 0xe1, 0xb0, 0x2d, 0x26, 0x94, 0x3b,
	0xb9, 0x69, 0xcd, 0xf9, 0x6f, 0x88, 0x7f, 0xcb, 0x5e, 0xa4, 0x0f, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x25, 0xe4, 0xfd, 0x96, 0xbb, 0x01, 0x00, 0x00,
}
